services:
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório atual no contêiner para refletir as alterações no código em tempo real
      - .:/app